name: 'Mosaic rush version report action'
description: 'Creates a version report for a Rush project'
inputs:
  report-id:
    description: 'Name of the report. Needs to follow a format of (AZaz-0-9) and be url-readable'
    required: true
  stack:
    description: 'Name of the stack, like dev or prod'
    required: true
    default: 'dev'
outputs:
  versionDetails:
    description: 'Project versions'
runs:
  using: 'node12'
  main: 'dist/index.js'